CREATE DATABASE zipdoc

CREATE TABLE IF NOT EXISTS priceTable (
    RTMS_ID  VARCHAR(50) NOT NULL PRIMARY KEY, -- 실거래가아이디
    LAND_CD  VARCHAR(15) NOT NULL, -- 지번코드
    SGG_CD 	 VARCHAR(10) NOT NULL, -- 시군구코드
	 SGG_NM   VARCHAR(10) NOT NULL, -- 자치구명
	 BJDONG10_CD  VARCHAR(20) NOT NULL, -- 법정동코드
	 BJDONG_NM  VARCHAR(10) NOT NULL, -- 법정동명
	 ACC_YEAR  VARCHAR(5) NOT NULL, -- 신고년도
	 JOB_GBN  VARCHAR(3) NOT NULL, -- 업무구분코드
	 JOB_GBN_NM  VARCHAR(10) NOT NULL, -- 업무구분
	 DEAL_YMD  VARCHAR(3) NULL, -- 계약일자
	 OBJ_SEQNO  VARCHAR(5) NOT NULL, -- 물건번호
	 TOT_AREA  VARCHAR(10) NOT NULL, -- 대지권면적
	 BLDG_AREA  VARCHAR(10) NOT NULL, -- 건물면적
	 RIGHT_GBN  VARCHAR(5) NOT NULL, -- 관리구분코드
	 FLR_INFO  VARCHAR(5) NOT NULL, -- 층정보
	 BLDG_MUSE_CD  VARCHAR(10) NOT NULL, -- 건물주용도코드
	 BLDG_MUSE_NM  VARCHAR(10) NOT NULL, -- 건물주용도
	 OBJ_AMT  VARCHAR(50) NOT NULL, -- 물건금액
	 BUILD_YEAR  VARCHAR(10) NOT NULL -- 건축년도
    )ENGINE=INNODB;	

-- 값 없는 컬럼
SELECT DISTINCT DEAL_YMD
FROM pricetable
;

-- DEAL_YMD 컬럼 삭제
ALTER TABLE pricetable DROP COLUMN DEAL_YMD;


SELECT DISTINCT RIGHT_GBN
FROM pricetable
;

-- RIGHT_GBN 컬럼 삭제
ALTER TABLE pricetable DROP COLUMN RIGHT_GBN;


SELECT DISTINCT build_year
FROM pricetable
ORDER BY build_year
;

-- BUILD_YEAR = 0인 데이터 삭제
DELETE FROM pricetable WHERE build_year = 0;


SELECT RTMS_ID
FROM pricetable
;

SELECT DISTINCT acc_year
FROM pricetable
ORDER BY acc_year
;

SELECT DISTINCT OBJ_AMT
FROM pricetable
ORDER BY OBJ_AMT
;

SELECT RTMS_ID,FLR_INFO
FROM pricetable
WHERE flr_info = '';

-- flr_info 데이터 중 공백인 값을 NULL 처리하기
UPDATE pricetable SET flr_info = NULL WHERE flr_info = '';

SELECT RTMS_ID,LAND_CD
FROM pricetable
WHERE LAND_CD = '';

-- LAND_CD 데이터 중 공백인 값을 NULL 처리하기
UPDATE pricetable SET LAND_CD = NULL WHERE LAND_CD = '';

SELECT RTMS_ID,SGG_NM
FROM pricetable
WHERE SGG_NM = '';

-- SGG_NM 데이터 중 공백인 값을 NULL 처리하기
UPDATE pricetable SET SGG_NM = NULL WHERE SGG_NM = '';

SELECT RTMS_ID,BJDONG_NM
FROM pricetable
WHERE BJDONG_NM = '';

-- BJDONG_NM 데이터 중 공백인 값을 NULL 처리하기
UPDATE pricetable SET BJDONG_NM = NULL WHERE BJDONG_NM = '';

SELECT RTMS_ID,ACC_YEAR
FROM pricetable
WHERE ACC_YEAR = '';

SELECT RTMS_ID,JOB_GBN_NM
FROM pricetable
WHERE JOB_GBN_NM = '';

SELECT RTMS_ID,OBJ_SEQNO
FROM pricetable
WHERE OBJ_SEQNO = '';

SELECT RTMS_ID,TOT_AREA
FROM pricetable
WHERE TOT_AREA = '';

-- BJDONG_NM 데이터 중 공백인 값을 NULL 처리하기
UPDATE pricetable SET TOT_AREA = NULL WHERE TOT_AREA = '';

SELECT RTMS_ID,BLDG_AREA
FROM pricetable
WHERE BLDG_AREA = '';


SELECT RTMS_ID,BLDG_MUSE_NM
FROM pricetable
WHERE BLDG_MUSE_NM = '';

SELECT RTMS_ID,OBJ_AMT
FROM pricetable
WHERE OBJ_AMT = '';

SELECT RTMS_ID,BUILD_YEAR
FROM pricetable
WHERE BUILD_YEAR = '';


-- NULL값 중 코드와 비교하여 입력할 수 있는 값 입력
-- BJDONG
SELECT RTMS_ID, BJDONG10_CD, BJDONG_NM
FROM pricetable
WHERE BJDONG_NM IS NULL
AND BJDONG10_CD != ''
;


SELECT RTMS_ID, BJDONG10_CD, BJDONG_NM
FROM pricetable
WHERE BJDONG10_CD = '4315011100'
;

SELECT RTMS_ID, BJDONG10_CD, BJDONG_NM
FROM pricetable
WHERE BJDONG10_CD = '4141010100'
;

-- SGG
SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_NM IS NULL
AND SGG_CD != ''
;

SELECT DISTINCT SGG_CD
FROM pricetable
WHERE SGG_NM IS NULL
AND SGG_CD != ''
;

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11110'
;

UPDATE pricetable SET SGG_NM = '종로구' WHERE SGG_NM IS NULL AND SGG_CD = '11110';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11140'
;

UPDATE pricetable SET SGG_NM = '중구' WHERE SGG_NM IS NULL AND SGG_CD = '11140';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11170'
;

UPDATE pricetable SET SGG_NM = '용산구' WHERE SGG_NM IS NULL AND SGG_CD = '11170';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11200'
;

UPDATE pricetable SET SGG_NM = '성동구' WHERE SGG_NM IS NULL AND SGG_CD = '11200';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11215'
;

UPDATE pricetable SET SGG_NM = '광진구' WHERE SGG_NM IS NULL AND SGG_CD = '11215';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11230'
;

UPDATE pricetable SET SGG_NM = '동대문구' WHERE SGG_NM IS NULL AND SGG_CD = '11230';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11260'
;

UPDATE pricetable SET SGG_NM = '중랑구' WHERE SGG_NM IS NULL AND SGG_CD = '11260';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11290'
;

UPDATE pricetable SET SGG_NM = '성북구' WHERE SGG_NM IS NULL AND SGG_CD = '11290';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11305'
;

UPDATE pricetable SET SGG_NM = '강북구' WHERE SGG_NM IS NULL AND SGG_CD = '11305';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11320'
;

UPDATE pricetable SET SGG_NM = '도봉구' WHERE SGG_NM IS NULL AND SGG_CD = '11320';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11350'
;

UPDATE pricetable SET SGG_NM = '노원구' WHERE SGG_NM IS NULL AND SGG_CD = '11350';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11380'
;

UPDATE pricetable SET SGG_NM = '은평구' WHERE SGG_NM IS NULL AND SGG_CD = '11380';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11410'
;

UPDATE pricetable SET SGG_NM = '서대문구' WHERE SGG_NM IS NULL AND SGG_CD = '11410';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11440'
;

UPDATE pricetable SET SGG_NM = '마포구' WHERE SGG_NM IS NULL AND SGG_CD = '11440';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11470'
;

UPDATE pricetable SET SGG_NM = '양천구' WHERE SGG_NM IS NULL AND SGG_CD = '11470';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11500'
;

UPDATE pricetable SET SGG_NM = '강서구' WHERE SGG_NM IS NULL AND SGG_CD = '11500';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11530'
;

UPDATE pricetable SET SGG_NM = '구로구' WHERE SGG_NM IS NULL AND SGG_CD = '11530';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11545'
;

UPDATE pricetable SET SGG_NM = '금천구' WHERE SGG_NM IS NULL AND SGG_CD = '11545';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11560'
;

UPDATE pricetable SET SGG_NM = '영등포구' WHERE SGG_NM IS NULL AND SGG_CD = '11560';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11590'
;

UPDATE pricetable SET SGG_NM = '동작구' WHERE SGG_NM IS NULL AND SGG_CD = '11590';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11620'
;

UPDATE pricetable SET SGG_NM = '관악구' WHERE SGG_NM IS NULL AND SGG_CD = '11620';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11650'
;

UPDATE pricetable SET SGG_NM = '서초구' WHERE SGG_NM IS NULL AND SGG_CD = '11650';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11680'
;

UPDATE pricetable SET SGG_NM = '강남구' WHERE SGG_NM IS NULL AND SGG_CD = '11680';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11710'
;

UPDATE pricetable SET SGG_NM = '송파구' WHERE SGG_NM IS NULL AND SGG_CD = '11710';

SELECT RTMS_ID, SGG_CD, SGG_NM
FROM pricetable
WHERE SGG_CD = '11740'
;

UPDATE pricetable SET SGG_NM = '강동구' WHERE SGG_NM IS NULL AND SGG_CD = '11740';


-- BLDG_MUSE
SELECT RTMS_ID, BLDG_MUSE_CD, BLDG_MUSE_NM
FROM pricetable
WHERE BLDG_MUSE_NM IS NULL
AND BLDG_MUSE_CD != ''
;

-- 전처리 완료.

-- seoul_house_price4.csv
SELECT RTMS_ID,SGG_NM,BJDONG_NM,TOT_AREA,BLDG_AREA,FLR_INFO,BLDG_MUSE_NM,OBJ_AMT,BUILD_YEAR
FROM pricetable
;

-- seoul_house_price5.csv
SELECT RTMS_ID,SGG_NM,BJDONG_NM,ACC_YEAR,TOT_AREA,BLDG_AREA,FLR_INFO,BLDG_MUSE_NM,OBJ_AMT,BUILD_YEAR
FROM pricetable
;

SELECT DISTINCT acc_year
FROM pricetable
;